// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.2
// source: protocol_buffers/gemini_service/gemini_service.proto

package gemini

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_buffers_gemini_service_gemini_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_buffers_gemini_service_gemini_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_protocol_buffers_gemini_service_gemini_service_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Option   int32  `protobuf:"varint,1,opt,name=option,proto3" json:"option,omitempty"`
	Response string `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Error    string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_buffers_gemini_service_gemini_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_buffers_gemini_service_gemini_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_protocol_buffers_gemini_service_gemini_service_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetOption() int32 {
	if x != nil {
		return x.Option
	}
	return 0
}

func (x *QueryResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_protocol_buffers_gemini_service_gemini_service_proto protoreflect.FileDescriptor

var file_protocol_buffers_gemini_service_gemini_service_proto_rawDesc = []byte{
	0x0a, 0x34, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x65,
	0x72, 0x73, 0x2f, 0x67, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x67, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x24, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x59, 0x0a, 0x0d,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x56, 0x0a, 0x06, 0x47, 0x65, 0x6d, 0x69, 0x6e,
	0x69, 0x12, 0x4c, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x65, 0x6d, 0x69, 0x6e, 0x69,
	0x12, 0x1c, 0x2e, 0x67, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x67, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42,
	0x13, 0x5a, 0x11, 0x62, 0x6d, 0x77, 0x61, 0x64, 0x66, 0x6f, 0x72, 0x74, 0x68, 0x2f, 0x67, 0x65,
	0x6d, 0x69, 0x6e, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_buffers_gemini_service_gemini_service_proto_rawDescOnce sync.Once
	file_protocol_buffers_gemini_service_gemini_service_proto_rawDescData = file_protocol_buffers_gemini_service_gemini_service_proto_rawDesc
)

func file_protocol_buffers_gemini_service_gemini_service_proto_rawDescGZIP() []byte {
	file_protocol_buffers_gemini_service_gemini_service_proto_rawDescOnce.Do(func() {
		file_protocol_buffers_gemini_service_gemini_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_buffers_gemini_service_gemini_service_proto_rawDescData)
	})
	return file_protocol_buffers_gemini_service_gemini_service_proto_rawDescData
}

var file_protocol_buffers_gemini_service_gemini_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_buffers_gemini_service_gemini_service_proto_goTypes = []interface{}{
	(*QueryRequest)(nil),  // 0: gemini_service.QueryRequest
	(*QueryResponse)(nil), // 1: gemini_service.QueryResponse
}
var file_protocol_buffers_gemini_service_gemini_service_proto_depIdxs = []int32{
	0, // 0: gemini_service.Gemini.QueryGemini:input_type -> gemini_service.QueryRequest
	1, // 1: gemini_service.Gemini.QueryGemini:output_type -> gemini_service.QueryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_buffers_gemini_service_gemini_service_proto_init() }
func file_protocol_buffers_gemini_service_gemini_service_proto_init() {
	if File_protocol_buffers_gemini_service_gemini_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_buffers_gemini_service_gemini_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_buffers_gemini_service_gemini_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_buffers_gemini_service_gemini_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_buffers_gemini_service_gemini_service_proto_goTypes,
		DependencyIndexes: file_protocol_buffers_gemini_service_gemini_service_proto_depIdxs,
		MessageInfos:      file_protocol_buffers_gemini_service_gemini_service_proto_msgTypes,
	}.Build()
	File_protocol_buffers_gemini_service_gemini_service_proto = out.File
	file_protocol_buffers_gemini_service_gemini_service_proto_rawDesc = nil
	file_protocol_buffers_gemini_service_gemini_service_proto_goTypes = nil
	file_protocol_buffers_gemini_service_gemini_service_proto_depIdxs = nil
}
