// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.2
// source: protocol_buffers/book_service/book_service.proto

package svc_template

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookServiceClient interface {
	CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*CreateBookResponse, error)
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*Book, error)
	GetBooksViaAuthor(ctx context.Context, in *GetBookViaAuthor, opts ...grpc.CallOption) (BookService_GetBooksViaAuthorClient, error)
	GetGreatestBook(ctx context.Context, opts ...grpc.CallOption) (BookService_GetGreatestBookClient, error)
	GetBooks(ctx context.Context, opts ...grpc.CallOption) (BookService_GetBooksClient, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*CreateBookResponse, error) {
	out := new(CreateBookResponse)
	err := c.cc.Invoke(ctx, "/svc_template.BookService/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/svc_template.BookService/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetBooksViaAuthor(ctx context.Context, in *GetBookViaAuthor, opts ...grpc.CallOption) (BookService_GetBooksViaAuthorClient, error) {
	stream, err := c.cc.NewStream(ctx, &BookService_ServiceDesc.Streams[0], "/svc_template.BookService/GetBooksViaAuthor", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookServiceGetBooksViaAuthorClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BookService_GetBooksViaAuthorClient interface {
	Recv() (*Book, error)
	grpc.ClientStream
}

type bookServiceGetBooksViaAuthorClient struct {
	grpc.ClientStream
}

func (x *bookServiceGetBooksViaAuthorClient) Recv() (*Book, error) {
	m := new(Book)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bookServiceClient) GetGreatestBook(ctx context.Context, opts ...grpc.CallOption) (BookService_GetGreatestBookClient, error) {
	stream, err := c.cc.NewStream(ctx, &BookService_ServiceDesc.Streams[1], "/svc_template.BookService/GetGreatestBook", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookServiceGetGreatestBookClient{stream}
	return x, nil
}

type BookService_GetGreatestBookClient interface {
	Send(*GetBookRequest) error
	CloseAndRecv() (*Book, error)
	grpc.ClientStream
}

type bookServiceGetGreatestBookClient struct {
	grpc.ClientStream
}

func (x *bookServiceGetGreatestBookClient) Send(m *GetBookRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bookServiceGetGreatestBookClient) CloseAndRecv() (*Book, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Book)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bookServiceClient) GetBooks(ctx context.Context, opts ...grpc.CallOption) (BookService_GetBooksClient, error) {
	stream, err := c.cc.NewStream(ctx, &BookService_ServiceDesc.Streams[2], "/svc_template.BookService/GetBooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookServiceGetBooksClient{stream}
	return x, nil
}

type BookService_GetBooksClient interface {
	Send(*emptypb.Empty) error
	Recv() (*Book, error)
	grpc.ClientStream
}

type bookServiceGetBooksClient struct {
	grpc.ClientStream
}

func (x *bookServiceGetBooksClient) Send(m *emptypb.Empty) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bookServiceGetBooksClient) Recv() (*Book, error) {
	m := new(Book)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookServiceServer is the server API for BookService service.
// All implementations must embed UnimplementedBookServiceServer
// for forward compatibility
type BookServiceServer interface {
	CreateBook(context.Context, *CreateBookRequest) (*CreateBookResponse, error)
	GetBook(context.Context, *GetBookRequest) (*Book, error)
	GetBooksViaAuthor(*GetBookViaAuthor, BookService_GetBooksViaAuthorServer) error
	GetGreatestBook(BookService_GetGreatestBookServer) error
	GetBooks(BookService_GetBooksServer) error
	mustEmbedUnimplementedBookServiceServer()
}

// UnimplementedBookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (UnimplementedBookServiceServer) CreateBook(context.Context, *CreateBookRequest) (*CreateBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (UnimplementedBookServiceServer) GetBook(context.Context, *GetBookRequest) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (UnimplementedBookServiceServer) GetBooksViaAuthor(*GetBookViaAuthor, BookService_GetBooksViaAuthorServer) error {
	return status.Errorf(codes.Unimplemented, "method GetBooksViaAuthor not implemented")
}
func (UnimplementedBookServiceServer) GetGreatestBook(BookService_GetGreatestBookServer) error {
	return status.Errorf(codes.Unimplemented, "method GetGreatestBook not implemented")
}
func (UnimplementedBookServiceServer) GetBooks(BookService_GetBooksServer) error {
	return status.Errorf(codes.Unimplemented, "method GetBooks not implemented")
}
func (UnimplementedBookServiceServer) mustEmbedUnimplementedBookServiceServer() {}

// UnsafeBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServiceServer will
// result in compilation errors.
type UnsafeBookServiceServer interface {
	mustEmbedUnimplementedBookServiceServer()
}

func RegisterBookServiceServer(s grpc.ServiceRegistrar, srv BookServiceServer) {
	s.RegisterService(&BookService_ServiceDesc, srv)
}

func _BookService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svc_template.BookService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).CreateBook(ctx, req.(*CreateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svc_template.BookService/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetBooksViaAuthor_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBookViaAuthor)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BookServiceServer).GetBooksViaAuthor(m, &bookServiceGetBooksViaAuthorServer{stream})
}

type BookService_GetBooksViaAuthorServer interface {
	Send(*Book) error
	grpc.ServerStream
}

type bookServiceGetBooksViaAuthorServer struct {
	grpc.ServerStream
}

func (x *bookServiceGetBooksViaAuthorServer) Send(m *Book) error {
	return x.ServerStream.SendMsg(m)
}

func _BookService_GetGreatestBook_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BookServiceServer).GetGreatestBook(&bookServiceGetGreatestBookServer{stream})
}

type BookService_GetGreatestBookServer interface {
	SendAndClose(*Book) error
	Recv() (*GetBookRequest, error)
	grpc.ServerStream
}

type bookServiceGetGreatestBookServer struct {
	grpc.ServerStream
}

func (x *bookServiceGetGreatestBookServer) SendAndClose(m *Book) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bookServiceGetGreatestBookServer) Recv() (*GetBookRequest, error) {
	m := new(GetBookRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BookService_GetBooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BookServiceServer).GetBooks(&bookServiceGetBooksServer{stream})
}

type BookService_GetBooksServer interface {
	Send(*Book) error
	Recv() (*emptypb.Empty, error)
	grpc.ServerStream
}

type bookServiceGetBooksServer struct {
	grpc.ServerStream
}

func (x *bookServiceGetBooksServer) Send(m *Book) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bookServiceGetBooksServer) Recv() (*emptypb.Empty, error) {
	m := new(emptypb.Empty)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookService_ServiceDesc is the grpc.ServiceDesc for BookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "svc_template.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBook",
			Handler:    _BookService_CreateBook_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _BookService_GetBook_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBooksViaAuthor",
			Handler:       _BookService_GetBooksViaAuthor_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetGreatestBook",
			Handler:       _BookService_GetGreatestBook_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetBooks",
			Handler:       _BookService_GetBooks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protocol_buffers/book_service/book_service.proto",
}
